/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hello message */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email with token */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend verification email */
        post: operations["AuthController_resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/expected-exam-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user's expected exam date */
        patch: operations["AuthController_updateExpectedExamDate"];
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all problems (admin only) */
        get: operations["ProblemsController_list"];
        put?: never;
        /** Create a new problem (admin only) */
        post: operations["ProblemsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}/clue-lens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clue Lens for a problem */
        get: operations["ProblemsController_getClueLens"];
        put?: never;
        /** Create or replace Clue Lens for a problem (admin only) */
        post: operations["ProblemsController_setClueLens"];
        /** Delete Clue Lens for a problem (admin only) */
        delete: operations["ProblemsController_deleteClueLens"];
        options?: never;
        head?: never;
        /** Update Clue Lens for a problem (admin only) */
        patch: operations["ProblemsController_updateClueLens"];
        trace?: never;
    };
    "/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem by id, optionally with translation */
        get: operations["ProblemsController_get"];
        put?: never;
        post?: never;
        /** Delete a problem (admin only) */
        delete: operations["ProblemsController_delete"];
        options?: never;
        head?: never;
        /** Update a problem (admin only) */
        patch: operations["ProblemsController_update"];
        trace?: never;
    };
    "/problems/{id}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a translation to a problem (admin only) */
        post: operations["ProblemsController_createTranslation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}/translations/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem translation */
        get: operations["ProblemsController_getTranslation"];
        put?: never;
        post?: never;
        /** Delete a problem translation (admin only) */
        delete: operations["ProblemsController_deleteTranslation"];
        options?: never;
        head?: never;
        /** Update a problem translation (admin only) */
        patch: operations["ProblemsController_updateTranslation"];
        trace?: never;
    };
    "/problem-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all problem sets (admin only) */
        get: operations["ProblemSetsController_list"];
        put?: never;
        /** Create a new problem set (admin only) */
        post: operations["ProblemSetsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problem-sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem set with its problems */
        get: operations["ProblemSetsController_get"];
        put?: never;
        post?: never;
        /** Delete a problem set (admin only) */
        delete: operations["ProblemSetsController_delete"];
        options?: never;
        head?: never;
        /** Update a problem set (admin only) */
        patch: operations["ProblemSetsController_update"];
        trace?: never;
    };
    "/solution-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user sessions */
        get: operations["SolutionSessionsController_list"];
        put?: never;
        /** Start a new solution session */
        post: operations["SolutionSessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solution-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a session with answers and progress */
        get: operations["SolutionSessionsController_get"];
        put?: never;
        post?: never;
        /** Delete a session */
        delete: operations["SolutionSessionsController_delete"];
        options?: never;
        head?: never;
        /** Update session status */
        patch: operations["SolutionSessionsController_update"];
        trace?: never;
    };
    "/solution-sessions/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer for a problem */
        post: operations["SolutionSessionsController_submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all categories */
        get: operations["CategoriesController_list"];
        put?: never;
        /** Create a new category (admin only) */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category by id */
        get: operations["CategoriesController_get"];
        put?: never;
        post?: never;
        /** Delete a category (admin only) */
        delete: operations["CategoriesController_delete"];
        options?: never;
        head?: never;
        /** Update a category (admin only) */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user progress by category */
        get: operations["ProgressController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/problem-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user progress by problem set */
        get: operations["ProgressController_getProblemSets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clue-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all clue groups (admin only) */
        get: operations["ClueWordsController_listGroups"];
        put?: never;
        /** Create a new clue group (admin only) */
        post: operations["ClueWordsController_createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clue-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a clue group by id (admin only) */
        get: operations["ClueWordsController_getGroup"];
        put?: never;
        post?: never;
        /** Delete a clue group (admin only) */
        delete: operations["ClueWordsController_deleteGroup"];
        options?: never;
        head?: never;
        /** Update a clue group (admin only) */
        patch: operations["ClueWordsController_updateGroup"];
        trace?: never;
    };
    "/admin/clue-groups/{groupId}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List words in a clue group (admin only) */
        get: operations["ClueWordsController_listWords"];
        put?: never;
        /** Create a clue word in a group (admin only) */
        post: operations["ClueWordsController_createWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/clue-groups/{groupId}/words/{wordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a clue word by id (admin only) */
        get: operations["ClueWordsController_getWord"];
        put?: never;
        post?: never;
        /** Delete a clue word (admin only) */
        delete: operations["ClueWordsController_deleteWord"];
        options?: never;
        head?: never;
        /** Update a clue word (admin only) */
        patch: operations["ClueWordsController_updateWord"];
        trace?: never;
    };
    "/admin/clue-groups/{groupId}/words/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder words in a clue group (admin only) */
        patch: operations["ClueWordsController_reorderWords"];
        trace?: never;
    };
    "/vocab/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all vocabulary sets */
        get: operations["VocabController_listSets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vocabulary set */
        get: operations["VocabController_getSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/sets/{id}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lesson words for a vocabulary set */
        get: operations["VocabController_listWords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vocab/sets/{id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get quiz questions for a vocabulary set */
        get: operations["VocabController_listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/vocab/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all vocabulary sets (admin only) */
        get: operations["VocabAdminController_listSets"];
        put?: never;
        /** Create a vocabulary set (admin only) */
        post: operations["VocabAdminController_createSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/vocab/sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vocabulary set (admin only) */
        get: operations["VocabAdminController_getSet"];
        put?: never;
        post?: never;
        /** Delete a vocabulary set (admin only) */
        delete: operations["VocabAdminController_deleteSet"];
        options?: never;
        head?: never;
        /** Update a vocabulary set (admin only) */
        patch: operations["VocabAdminController_updateSet"];
        trace?: never;
    };
    "/admin/vocab/sets/{id}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List words in a vocab set (admin only) */
        get: operations["VocabAdminController_listWords"];
        put?: never;
        /** Create a vocab word in a set (admin only) */
        post: operations["VocabAdminController_createWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/vocab/sets/{id}/words/{wordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vocab word by id (admin only) */
        get: operations["VocabAdminController_getWord"];
        put?: never;
        post?: never;
        /** Delete a vocab word (admin only) */
        delete: operations["VocabAdminController_deleteWord"];
        options?: never;
        head?: never;
        /** Update a vocab word (admin only) */
        patch: operations["VocabAdminController_updateWord"];
        trace?: never;
    };
    "/admin/vocab/sets/{id}/words/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder words in a vocab set (admin only) */
        patch: operations["VocabAdminController_reorderWords"];
        trace?: never;
    };
    "/admin/vocab/sets/{id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quiz questions in a vocab set (admin only) */
        get: operations["VocabAdminController_listQuestions"];
        put?: never;
        /** Create a vocab quiz question (admin only) */
        post: operations["VocabAdminController_createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/vocab/sets/{id}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a vocab quiz question (admin only) */
        get: operations["VocabAdminController_getQuestion"];
        put?: never;
        post?: never;
        /** Delete a vocab quiz question (admin only) */
        delete: operations["VocabAdminController_deleteQuestion"];
        options?: never;
        head?: never;
        /** Update a vocab quiz question (admin only) */
        patch: operations["VocabAdminController_updateQuestion"];
        trace?: never;
    };
    "/admin/vocab/sets/{id}/questions/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder questions in a vocab set (admin only) */
        patch: operations["VocabAdminController_reorderQuestions"];
        trace?: never;
    };
    "/payments/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Stripe checkout session */
        post: operations["PaymentController_createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/session/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify a checkout session and activate subscription */
        get: operations["PaymentController_verifySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe webhook handler */
        post: operations["PaymentController_handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example password123 */
            password: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        RefreshDto: {
            /** @example eyJhbGciOiJIUzI1NiIs... */
            refreshToken: string;
        };
        VerifyEmailDto: {
            /** @example abc123... */
            token: string;
        };
        ResendVerificationDto: {
            /** @example user@example.com */
            email: string;
        };
        ForgotPasswordDto: {
            /** @example user@example.com */
            email: string;
        };
        ResetPasswordDto: {
            /** @example reset-token-string */
            token: string;
            /** @example newpassword123 */
            password: string;
        };
        UpdateExpectedExamDateDto: {
            /**
             * @description Expected exam date in YYYY-MM-DD format. Send null to clear.
             * @example 2026-07-07
             */
            expectedExamDate?: Record<string, never> | null;
        };
        FocusWordDto: {
            /** @example 15 vuotta täyttäneen */
            phrase: string;
            /** @example once turned 15 */
            translation: string;
        };
        WordTranslationDto: {
            /** @example Kuljettaja */
            word: string;
            /** @example the driver */
            translation: string;
        };
        OptionClueDto: {
            /**
             * @description Zero-based option index
             * @example 0
             */
            optionIndex: number;
            /** @enum {string} */
            type: "trap" | "good";
            wordTranslations: components["schemas"]["WordTranslationDto"][];
        };
        ClueLensDto: {
            focusWords: components["schemas"]["FocusWordDto"][];
            optionClues: components["schemas"]["OptionClueDto"][];
        };
        CreateProblemDto: {
            /** @example What is 2 + 2? */
            text: string;
            /**
             * @example [
             *       "1",
             *       "2",
             *       "3",
             *       "4"
             *     ]
             */
            options: string[];
            /**
             * @description Zero-based index of correct option
             * @example 3
             */
            correctAnswer: number;
            /**
             * @description Explanation shown after answering
             * @example 2 + 2 equals 4 because we are adding two twos.
             */
            explanation?: string;
            /**
             * @description Static image asset key used by the frontend
             * @example Q284
             */
            imageKey?: string;
            /**
             * @description Optional ID of the default problem translation
             * @example k57a1...
             */
            defaultTranslationId?: string;
            clueLens?: components["schemas"]["ClueLensDto"];
            /**
             * @description Optional linked vocabulary word ID
             * @example set-1-w1
             */
            vocabWordId?: string;
        };
        CreateClueLensDto: {
            focusWords: components["schemas"]["FocusWordDto"][];
            optionClues: components["schemas"]["OptionClueDto"][];
        };
        UpdateClueLensDto: {
            focusWords?: components["schemas"]["FocusWordDto"][];
            optionClues?: components["schemas"]["OptionClueDto"][];
        };
        CreateProblemTranslationDto: {
            /** @example en */
            locale: string;
            /** @example Which of the following is correct... */
            text: string;
            /**
             * @example [
             *       "Option A",
             *       "Option B",
             *       "Option C"
             *     ]
             */
            options: string[];
        };
        UpdateProblemTranslationDto: {
            /** @example Which of the following is correct... */
            text?: string;
            /**
             * @example [
             *       "Option A",
             *       "Option B",
             *       "Option C"
             *     ]
             */
            options?: string[];
        };
        UpdateProblemDto: {
            /** @example What is 2 + 2? */
            text?: string;
            /**
             * @example [
             *       "1",
             *       "2",
             *       "3",
             *       "4"
             *     ]
             */
            options?: string[];
            /**
             * @description Zero-based index of correct option
             * @example 3
             */
            correctAnswer?: number;
            /**
             * @description Explanation shown after answering
             * @example 2 + 2 equals 4 because we are adding two twos.
             */
            explanation?: string;
            /**
             * @description Static image asset key used by the frontend
             * @example Q284
             */
            imageKey?: string;
            /**
             * @description Optional ID of the default problem translation
             * @example k57a1...
             */
            defaultTranslationId?: string;
            clueLens?: components["schemas"]["UpdateClueLensDto"];
            /**
             * @description Optional linked vocabulary word ID
             * @example set-1-w1
             */
            vocabWordId?: string;
        };
        CreateProblemSetDto: {
            /** @example Basic Math Quiz */
            label: string;
            /**
             * @description Array of problem IDs
             * @example []
             */
            problems: string[];
            /**
             * @description Category ID
             * @example category-id
             */
            categoryId?: string;
            /**
             * @description Optional linked vocabulary set ID
             * @example set-1
             */
            vocabSetId?: string;
        };
        UpdateProblemSetDto: {
            /** @example Basic Math Quiz */
            label?: string;
            /**
             * @description Array of problem IDs
             * @example []
             */
            problems?: string[];
            /**
             * @description Category ID
             * @example category-id
             */
            categoryId?: string;
            /**
             * @description Optional linked vocabulary set ID
             * @example set-1
             */
            vocabSetId?: string;
        };
        CreateSolutionSessionDto: {
            /**
             * @description Problem set ID
             * @example problemSet123
             */
            problemSetId: string;
        };
        SubmitAnswerDto: {
            /**
             * @description Problem ID
             * @example problem123
             */
            problemId: string;
            /**
             * @description Zero-based index of selected option
             * @example 1
             */
            selectedAnswer: number;
        };
        UpdateSolutionSessionDto: {
            /** @enum {string} */
            status?: "in_progress" | "completed" | "abandoned";
        };
        CreateCategoryDto: {
            /** @example Passenger Help & Safety */
            name: string;
            /** @enum {string} */
            type: "main" | "sub";
            /** @example parent-category-id */
            parentCategoryId?: string;
            /** @example 1 */
            sortOrder?: number;
        };
        UpdateCategoryDto: {
            /** @example Passenger Help & Safety */
            name?: string;
            /** @enum {string} */
            type?: "main" | "sub";
            /** @example parent-category-id */
            parentCategoryId?: string;
            /** @example 1 */
            sortOrder?: number;
        };
        CreateClueGroupDto: {
            /**
             * @description Unique slug-like id
             * @example positive
             */
            id: string;
            /** @example Positive */
            short: string;
            /** @example Positive clue words */
            label: string;
            /** @enum {string} */
            tone: "positive" | "negative" | "neutral";
            /** @example Words that indicate a favorable answer */
            blurb: string;
            /** @example 1 */
            order: number;
            /**
             * @description Optional external problem set id
             * @example problemSet123
             */
            problemSetId?: Record<string, never> | null;
        };
        UpdateClueGroupDto: {
            /** @example Positive */
            short?: string;
            /** @example Positive clue words */
            label?: string;
            /** @enum {string} */
            tone?: "positive" | "negative" | "neutral";
            /** @example Words that indicate a favorable answer */
            blurb?: string;
            /** @example 1 */
            order?: number;
            /**
             * @description Optional external problem set id
             * @example problemSet123
             */
            problemSetId?: Record<string, never> | null;
        };
        CreateClueWordDto: {
            /**
             * @description Optional explicit id; generated if omitted
             * @example clue-positive-w3
             */
            id?: string;
            /** @example aina */
            phraseFi: string;
            /** @example always */
            meaningEn: string;
            /** @example Suggests the action is required */
            effectEn?: Record<string, never> | null;
            /** @example Unless stated otherwise */
            exceptionEn?: Record<string, never> | null;
        };
        UpdateClueWordDto: {
            /** @example aina */
            phraseFi?: string;
            /** @example always */
            meaningEn?: string;
            /** @example Suggests the action is required */
            effectEn?: Record<string, never> | null;
            /** @example Unless stated otherwise */
            exceptionEn?: Record<string, never> | null;
        };
        ReorderClueWordsDto: {
            /**
             * @description Word ids in the desired order
             * @example [
             *       "clue-positive-w2",
             *       "clue-positive-w1"
             *     ]
             */
            wordIds: string[];
        };
        CreateVocabSetDto: {
            /**
             * @description URL-safe unique ID
             * @example set-1
             */
            id: string;
            /**
             * @description Set number
             * @example 1
             */
            setNo: number;
            /** @example Passenger Assistance & Accessibility — Part 1 */
            name: string;
            /**
             * @description App-facing category slug
             * @example special_needs
             */
            categoryId?: string;
            /**
             * @description Display order
             * @example 1
             */
            order: number;
        };
        UpdateVocabSetDto: {
            /**
             * @description Set number
             * @example 1
             */
            setNo?: number;
            /** @example Passenger Assistance & Accessibility — Part 1 */
            name?: string;
            /**
             * @description App-facing category slug
             * @example special_needs
             */
            categoryId?: string;
            /**
             * @description Display order
             * @example 1
             */
            order?: number;
        };
        VocabFormDto: {
            /** @example toimia */
            fi: string;
            /** @example to act */
            en: string;
        };
        CreateVocabWordDto: {
            /** @example set-1-w1 */
            id?: string;
            /** @example toimia */
            wordFi: string;
            /** @example to act / handle the situation */
            meaningEn: string;
            formsFi: components["schemas"]["VocabFormDto"][];
            /** @example Action keyword. It appears in questions asking what the driver should do. */
            examUseEn: string;
        };
        UpdateVocabWordDto: {
            /** @example toimia */
            wordFi?: string;
            /** @example to act / handle the situation */
            meaningEn?: string;
            formsFi?: components["schemas"]["VocabFormDto"][];
            /** @example Action keyword. It appears in questions asking what the driver should do. */
            examUseEn?: string;
        };
        ReorderVocabWordsDto: {
            /**
             * @example [
             *       "set-1-w2",
             *       "set-1-w1"
             *     ]
             */
            wordIds: string[];
        };
        CreateVocabQuestionDto: {
            /** @example toimia */
            promptWordFi: string;
            /**
             * @description Options in A, B, C order
             * @example [
             *       "to act / handle the situation",
             *       "wheelchair",
             *       "assistant/helper"
             *     ]
             */
            options: string[];
            /**
             * @example A
             * @enum {string}
             */
            correctOption: "A" | "B" | "C";
            /** @example to act / handle the situation */
            correctMeaningEn: string;
            /** @example set-1-w1 */
            lessonWordId?: string;
        };
        UpdateVocabQuestionDto: {
            /** @example toimia */
            promptWordFi?: string;
            /**
             * @description Options in A, B, C order
             * @example [
             *       "to act / handle the situation",
             *       "wheelchair",
             *       "assistant/helper"
             *     ]
             */
            options?: string[];
            /**
             * @example A
             * @enum {string}
             */
            correctOption?: "A" | "B" | "C";
            /** @example to act / handle the situation */
            correctMeaningEn?: string;
            /** @example set-1-w1 */
            lessonWordId?: string;
        };
        ReorderVocabQuestionsDto: {
            /**
             * @example [
             *       "j57a1...",
             *       "j57a2..."
             *     ]
             */
            questionIds: string[];
        };
        CreateCheckoutSessionDto: Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns hello message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns ok status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            /** @description Email verified successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationDto"];
            };
        };
        responses: {
            /** @description Verification email resent if account exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Reset email sent if account exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updateExpectedExamDate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpectedExamDateDto"];
            };
        };
        responses: {
            /** @description Expected exam date updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email not verified */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problems returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemDto"];
            };
        };
        responses: {
            /** @description Problem created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_getClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue lens returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_setClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClueLensDto"];
            };
        };
        responses: {
            /** @description Clue lens created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_deleteClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue lens deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue lens not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_updateClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClueLensDto"];
            };
        };
        responses: {
            /** @description Clue lens updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue lens not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_get: {
        parameters: {
            query: {
                locale: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemDto"];
            };
        };
        responses: {
            /** @description Problem updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_createTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemTranslationDto"];
            };
        };
        responses: {
            /** @description Translation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_getTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Translation returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Translation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_deleteTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Translation deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Translation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_updateTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locale: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemTranslationDto"];
            };
        };
        responses: {
            /** @description Translation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Translation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem sets returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemSetDto"];
            };
        };
        responses: {
            /** @description Problem set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem set returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem set deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemSetDto"];
            };
        };
        responses: {
            /** @description Problem set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSolutionSessionDto"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSolutionSessionDto"];
            };
        };
        responses: {
            /** @description Session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerDto"];
            };
        };
        responses: {
            /** @description Answer submitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid answer or session completed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Category not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProgressController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProgressController_getProblemSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem set progress returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue groups returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClueGroupDto"];
            };
        };
        responses: {
            /** @description Clue group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate id */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue group returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue group deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClueGroupDto"];
            };
        };
        responses: {
            /** @description Clue group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_listWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue words returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_createWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClueWordDto"];
            };
        };
        responses: {
            /** @description Clue word created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_getWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue word returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_deleteWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue word deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_updateWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClueWordDto"];
            };
        };
        responses: {
            /** @description Clue word updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClueWordsController_reorderWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderClueWordsDto"];
            };
        };
        responses: {
            /** @description Words reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabController_listSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab sets returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabController_getSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab set returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabController_listWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab words returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabController_listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab questions returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_listSets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab sets returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_createSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVocabSetDto"];
            };
        };
        responses: {
            /** @description Vocab set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_getSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab set returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_deleteSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab set deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_updateSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVocabSetDto"];
            };
        };
        responses: {
            /** @description Vocab set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_listWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab words returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_createWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVocabWordDto"];
            };
        };
        responses: {
            /** @description Vocab word created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_getWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vocab word returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vocab word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_deleteWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_updateWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVocabWordDto"];
            };
        };
        responses: {
            /** @description Vocab word updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_reorderWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderVocabWordsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_listQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVocabQuestionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVocabQuestionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VocabAdminController_reorderQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderVocabQuestionsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_createCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionDto"];
            };
        };
        responses: {
            /** @description Checkout session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_verifySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_handleWebhook: {
        parameters: {
            query?: never;
            header: {
                "stripe-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
