/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get hello message */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all problems (admin only) */
        get: operations["ProblemsController_list"];
        put?: never;
        /** Create a new problem (admin only) */
        post: operations["ProblemsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}/clue-lens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clue Lens for a problem */
        get: operations["ProblemsController_getClueLens"];
        put?: never;
        /** Create or replace Clue Lens for a problem (admin only) */
        post: operations["ProblemsController_setClueLens"];
        /** Delete Clue Lens for a problem (admin only) */
        delete: operations["ProblemsController_deleteClueLens"];
        options?: never;
        head?: never;
        /** Update Clue Lens for a problem (admin only) */
        patch: operations["ProblemsController_updateClueLens"];
        trace?: never;
    };
    "/problems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem by id, optionally with translation */
        get: operations["ProblemsController_get"];
        put?: never;
        post?: never;
        /** Delete a problem (admin only) */
        delete: operations["ProblemsController_delete"];
        options?: never;
        head?: never;
        /** Update a problem (admin only) */
        patch: operations["ProblemsController_update"];
        trace?: never;
    };
    "/problems/{id}/translations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a translation to a problem (admin only) */
        post: operations["ProblemsController_createTranslation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems/{id}/translations/{locale}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem translation */
        get: operations["ProblemsController_getTranslation"];
        put?: never;
        post?: never;
        /** Delete a problem translation (admin only) */
        delete: operations["ProblemsController_deleteTranslation"];
        options?: never;
        head?: never;
        /** Update a problem translation (admin only) */
        patch: operations["ProblemsController_updateTranslation"];
        trace?: never;
    };
    "/problem-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all problem sets (admin only) */
        get: operations["ProblemSetsController_list"];
        put?: never;
        /** Create a new problem set (admin only) */
        post: operations["ProblemSetsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problem-sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a problem set with its problems */
        get: operations["ProblemSetsController_get"];
        put?: never;
        post?: never;
        /** Delete a problem set (admin only) */
        delete: operations["ProblemSetsController_delete"];
        options?: never;
        head?: never;
        /** Update a problem set (admin only) */
        patch: operations["ProblemSetsController_update"];
        trace?: never;
    };
    "/solution-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user sessions */
        get: operations["SolutionSessionsController_list"];
        put?: never;
        /** Start a new solution session */
        post: operations["SolutionSessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solution-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a session with answers and progress */
        get: operations["SolutionSessionsController_get"];
        put?: never;
        post?: never;
        /** Delete a session */
        delete: operations["SolutionSessionsController_delete"];
        options?: never;
        head?: never;
        /** Update session status */
        patch: operations["SolutionSessionsController_update"];
        trace?: never;
    };
    "/solution-sessions/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer for a problem */
        post: operations["SolutionSessionsController_submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example John Doe */
            name: string;
            /** @example password123 */
            password: string;
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        RefreshDto: {
            /** @example eyJhbGciOiJIUzI1NiIs... */
            refreshToken: string;
        };
        ForgotPasswordDto: {
            /** @example user@example.com */
            email: string;
        };
        ResetPasswordDto: {
            /** @example reset-token-string */
            token: string;
            /** @example newpassword123 */
            password: string;
        };
        FocusWordDto: {
            /** @example 15 vuotta täyttäneen */
            phrase: string;
            /** @example once turned 15 */
            translation: string;
        };
        WordTranslationDto: {
            /** @example Kuljettaja */
            word: string;
            /** @example the driver */
            translation: string;
        };
        OptionClueDto: {
            /**
             * @description Zero-based option index
             * @example 0
             */
            optionIndex: number;
            /** @enum {string} */
            type: "trap" | "good";
            wordTranslations: components["schemas"]["WordTranslationDto"][];
        };
        ClueLensDto: {
            focusWords: components["schemas"]["FocusWordDto"][];
            optionClues: components["schemas"]["OptionClueDto"][];
        };
        CreateProblemDto: {
            /** @example What is 2 + 2? */
            text: string;
            /**
             * @example [
             *       "1",
             *       "2",
             *       "3",
             *       "4"
             *     ]
             */
            options: string[];
            /**
             * @description Zero-based index of correct option
             * @example 3
             */
            correctAnswer: number;
            /**
             * @description Explanation shown after answering
             * @example 2 + 2 equals 4 because we are adding two twos.
             */
            explanation?: string;
            /**
             * @description Static image asset key used by the frontend
             * @example Q284
             */
            imageKey?: string;
            clueLens?: components["schemas"]["ClueLensDto"];
        };
        CreateClueLensDto: {
            focusWords: components["schemas"]["FocusWordDto"][];
            optionClues: components["schemas"]["OptionClueDto"][];
        };
        UpdateClueLensDto: {
            focusWords?: components["schemas"]["FocusWordDto"][];
            optionClues?: components["schemas"]["OptionClueDto"][];
        };
        CreateProblemTranslationDto: {
            /** @example en */
            locale: string;
            /** @example Which of the following is correct... */
            text: string;
            /**
             * @example [
             *       "Option A",
             *       "Option B",
             *       "Option C"
             *     ]
             */
            options: string[];
        };
        UpdateProblemTranslationDto: {
            /** @example Which of the following is correct... */
            text?: string;
            /**
             * @example [
             *       "Option A",
             *       "Option B",
             *       "Option C"
             *     ]
             */
            options?: string[];
        };
        UpdateProblemDto: {
            /** @example What is 2 + 2? */
            text?: string;
            /**
             * @example [
             *       "1",
             *       "2",
             *       "3",
             *       "4"
             *     ]
             */
            options?: string[];
            /**
             * @description Zero-based index of correct option
             * @example 3
             */
            correctAnswer?: number;
            /**
             * @description Explanation shown after answering
             * @example 2 + 2 equals 4 because we are adding two twos.
             */
            explanation?: string;
            /**
             * @description Static image asset key used by the frontend
             * @example Q284
             */
            imageKey?: string;
            clueLens?: components["schemas"]["UpdateClueLensDto"];
        };
        CreateProblemSetDto: {
            /** @example Basic Math Quiz */
            label: string;
            /**
             * @description Array of problem IDs
             * @example []
             */
            problems: string[];
        };
        UpdateProblemSetDto: {
            /** @example Basic Math Quiz */
            label?: string;
            /**
             * @description Array of problem IDs
             * @example []
             */
            problems?: string[];
        };
        CreateSolutionSessionDto: {
            /**
             * @description Problem set ID
             * @example problemSet123
             */
            problemSetId: string;
        };
        SubmitAnswerDto: {
            /**
             * @description Problem ID
             * @example problem123
             */
            problemId: string;
            /**
             * @description Zero-based index of selected option
             * @example 1
             */
            selectedAnswer: number;
        };
        UpdateSolutionSessionDto: {
            /** @enum {string} */
            status?: "in_progress" | "completed" | "abandoned";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns hello message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns ok status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Reset email sent if account exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problems returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemDto"];
            };
        };
        responses: {
            /** @description Problem created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_getClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue lens returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_setClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClueLensDto"];
            };
        };
        responses: {
            /** @description Clue lens created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_deleteClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Clue lens deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue lens not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_updateClueLens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClueLensDto"];
            };
        };
        responses: {
            /** @description Clue lens updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Clue lens not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_get: {
        parameters: {
            query: {
                locale: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemDto"];
            };
        };
        responses: {
            /** @description Problem updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_createTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemTranslationDto"];
            };
        };
        responses: {
            /** @description Translation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_getTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Translation returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Translation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_deleteTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locale: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Translation deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Translation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemsController_updateTranslation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                locale: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemTranslationDto"];
            };
        };
        responses: {
            /** @description Translation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Translation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem sets returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProblemSetDto"];
            };
        };
        responses: {
            /** @description Problem set created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem set returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Problem set deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProblemSetsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProblemSetDto"];
            };
        };
        responses: {
            /** @description Problem set updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem set not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSolutionSessionDto"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSolutionSessionDto"];
            };
        };
        responses: {
            /** @description Session updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SolutionSessionsController_submitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerDto"];
            };
        };
        responses: {
            /** @description Answer submitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid answer or session completed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
